In [5]:
import numpy as np
import pandas as pd

In [6]:
a = np.array([[2,3,4], [1, 3, 4], [2, 2, 2]

])

In [7]:
for cell in a:
    print (cell)

[2 3 4]
[1 3 4]
[2 2 2]


In [8]:
for row in a:
    print (row)

[2 3 4]
[1 3 4]
[2 2 2]


In [9]:
for row in a.flat:
    print (row)

2
3
4
1
3
4
2
2
2


In [10]:
for cell in a:
    print (cell[2])

4
4
2


In [12]:
df = pd.read_csv('UBAO.csv', nrows = 50)
df

Date   Open   High    Low  Close    Volume  Adj Close
0    2/25/2011  32.29  33.09  32.27  10.00  20846500      32.95
1    2/24/2011  32.10  32.41  31.64  10.40  23416300      32.25
2    2/23/2011  32.55  32.65  32.02  10.50  22150000      32.18
3    2/22/2011  33.29  33.66  32.52  10.50  24878000      32.53
4    2/18/2011  33.02  33.71  32.91  10.50  25539300      33.68
5    2/17/2011  32.97  33.20  32.76  10.50  14568600      33.01
6    2/16/2011  32.85  33.14  32.61  10.53  15820900      33.11
7    2/15/2011  33.12  33.15  32.61  10.34  19330500      32.76
8    2/14/2011  33.29  33.54  33.24  10.88  16433900      33.29
9    2/11/2011  33.07  33.59  33.03  10.40  17396700      33.47
10   2/10/2011  32.78  33.26  32.66  10.44  17237700      33.26
11    2/9/2011  33.04  33.10  32.61  10.45  17110900      32.89
12    2/8/2011  33.02  33.16  32.72  10.31  15418100      33.03
13    2/7/2011  32.70  33.29  32.55  10.20  22780300      32.98
14    2/4/2011  32.92  32.98  32.53  10.30  38688800      32.62
15    2/3/2011  32.98  33.16  32.72  10.30  17600700      32.99
16    2/2/2011  33.09  33.56  33.00  10.42  19357900      33.14
17    2/1/2011  32.17  33.43  32.11   9.93  32573500      33.24
18   1/31/2011  31.95  32.20  31.84  10.45  20819700      32.03
19   1/28/2011  33.20  33.30  31.83  11.00  30818200      32.00
20   1/27/2011  32.62  33.09  32.16  11.17  25630200      32.92
21   1/26/2011  32.31  32.73  32.16  11.65  21482200      32.56
22   1/25/2011  32.39  32.44  31.94  11.70  25926700      32.29
23   1/24/2011  32.58  32.65  32.07  11.70  20169400      32.40
24   1/21/2011  32.47  32.68  32.34  11.50  34478400      32.51
25   1/20/2011  31.47  32.35  31.47  11.48  47745000      32.31
26   1/19/2011  31.36  31.61  31.28  11.45  26931300      31.60
27   1/18/2011  31.26  31.55  31.23  10.94  26972100      31.53
28   1/14/2011  31.02  31.34  30.94  10.61  37933800      31.25
29   1/13/2011  30.97  31.39  30.90  10.60  43411700      31.13
30   1/12/2011  31.22  31.23  30.94  10.40  33962200      30.90
31   1/11/2011  31.08  31.10  30.86  10.12  26389200      30.94
32   1/10/2011  30.85  31.22  30.80   9.97  29719300      30.99
33    1/7/2011  31.24  31.34  30.93   9.80  27695600      30.98
34    1/6/2011  31.19  31.20  31.02  10.00  21856800      31.12
35    1/5/2011  31.32  31.44  30.98  10.20  36339700      30.99
36    1/4/2011  31.60  31.75  31.14   9.97  22870600      31.43
37    1/3/2011  31.59  31.94  31.53   9.50  20969500      31.57
38  12/31/2010  31.22  31.33  30.93   9.15  11716300      31.25
39  12/30/2010  31.45  31.58  31.21   9.15  12988900      31.24
40  12/29/2010  31.53  31.69  31.42   9.17   9768900      31.45
41  12/28/2010  31.66  31.76  31.41   9.15   9734000      31.52
42  12/27/2010  31.40  31.80  31.24   9.18  13821300      31.61
43  12/23/2010  31.53  31.70  31.41   8.90  13046900      31.49
44  12/22/2010  31.68  31.88  31.56   8.55  14019200      31.61
45  12/21/2010  31.65  32.00  31.59   8.60  20000500      31.71
46  12/20/2010  31.54  31.94  31.11   8.50  33568200      31.63
47  12/17/2010  31.92  32.27  31.37   8.39  92487200      31.41
48  12/16/2010  30.70  30.77  30.25   8.50  47435700      30.22
49  12/15/2010  30.59  30.70  30.26   8.30  30537700      30.44